### ISSUE TITLE
Support sphinx 6.0+

### ISSUE THREAD

**Issue by harshil21** [readthedocs/readthedocs-sphinx-search#126]
Since sphinx 6.0, they have removed support of the jQuery and underscore.js frameworks (https://www.sphinx-doc.org/en/master/changes.html#id37). This makes this library unusable until we adopt the workaround mentioned or downgrade to sphinx 5.

**Comment by harshil21** [comment]
I've [already supported](https://github.com/harshil21/furo-sphinx-search/commit/6c05dbac0bb1be1803afa87d1170b99de280a39d) sphinx 6.0 in my [fork](https://github.com/harshil21/furo-sphinx-search/), let me know if those I can make those changes (or similar) here as well.

**Comment by stsewd** [comment]
Hi there! We were migrating to vanilla js, but the animations were the only thing missing migrating. @agjohnson do you have any opinions on keeping jquery for the animations or are we ok using vanilla js for that?

**Comment by agjohnson** [comment]
I don't have any strong opinions, but will note that to accomplish animations without jQuery, you'll be using CSS, not JS. jQuery is mostly just manipulating CSS properties (mostly `transition` and friends), though early on jQuery did some strong hacks for cross-browser animations as well.

The other option would be to conditionally use animations if jQuery is available. This will lead to some disparity in UX, but perhaps the animation issue is something we can polish up more later.

**Comment by stsewd** [comment]
Support for sphinx 6 was added in https://github.com/readthedocs/readthedocs-sphinx-search/pull/127, and we did a release yesterday.
