### ISSUE TITLE
Update to use Search api V3

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs-sphinx-search#131]
Update the API to call our new API:

https://docs.readthedocs.io/en/stable/server-side-search/api.html#api-v3

**Comment by stsewd** [comment]
I was working on this, and since we will be releasing a breaking change, we could take the opportunity to change the JS to make it more like a library  https://github.com/readthedocs/readthedocs-sphinx-search/issues/67#issuecomment-1457212444.

**Comment by ericholscher** [comment]
@stsewd I'm on board with that 👍
