### ISSUE TITLE
sphinx-search and sphinx-intersphinx

### ISSUE THREAD

**Issue by jaygray0919** [readthedocs/readthedocs-sphinx-search#138]
If I use `intersphinx` to link other `sphinx` instances e.g.
```
intersphinx_mapping = {
    'ewb': ('https://ewb.readthedocs.io/en/latest/', None),
    'rdf': ('https://rdfabout.readthedocs.io/en/latest/', None),
}
```
how to configure `sphinx-search` to search those instances for a specified string?

For example, looking here: https://readthedocs-sphinx-search.readthedocs.io/en/latest/customization.html#custom-styles
```
<a href="/api-v2?highlight=api">
              <h2 class="search__result__title">
                     API v2
                     <br />
              </h2>
 </a>
```
Search is relative to the page from which the search is launched.

Is it possible to specify other search domains - following the `intersphinx` method to `:ref:` another `sphinx` instance?

**Comment by stsewd** [comment]
Hi, you can use our search filter options, see https://readthedocs-sphinx-search.readthedocs.io/en/latest/configuration.html#confval-rtd_sphinx_search_default_filter, and https://docs.readthedocs.io/en/stable/server-side-search/syntax.html.

**Comment by jaygray0919** [comment]
Thanks - will do this now
/jay
