### ISSUE TITLE
Automatically "wildcard search"?

### ISSUE THREAD

**Issue by thephez** [readthedocs/readthedocs-sphinx-search#142]
Is there a way to configure search to act as if a wildcard (`*`) is present at the end of the user-entered search string? Based on feedback I've received, this behavior is expected by some and they think the search is broken since it doesn't do that (by default). I didn't see anything about this in the docs, but may have overlooked something.

**Comment by thephez** [comment]
That's not entirely surprising, but I figured it didn't hurt to ask. Thanks for the info!

**Comment by stsewd** [comment]
Opened https://github.com/readthedocs/readthedocs.org/issues/10568, since I think this feature would be useful.

**Comment by thephez** [comment]
> Opened [readthedocs/readthedocs.org#10568](https://github.com/readthedocs/readthedocs.org/issues/10568), since I think this feature would be useful.

Great, thanks!
