### ISSUE TITLE
Result on same page does not hide the search box

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-sphinx-search#26]
## Steps to reproduce it

1. search for a term (for example a configuration option)
1. click on the result to go to the Configuration page
1. click on the search again
1. search for another term that has a hit in the configuration page (but different anchor)
1. click on that result

## Expected result

Move to the section of the hit and hide the search box.

## Actual result

Search box is not hidden.

> NOTE: I'm using "Configuratio page" as example but the required thing is to be the same page in both results

**Comment by dojutsu-user** [comment]
@humitos 
Can you test this again?
It seems like this is not valid anymore.

**Comment by humitos** [comment]
Yes. This issue is solved. Closing. Thanks!
