### ISSUE TITLE
Hitting Enter uses the default search page

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-sphinx-search#40]
### Steps to reproduce it

1. go to https://docs.readthedocs.io/en/latest/
1. click on search
1. type `configuration`
1. hit Enter

### Actual result

You are redirected to https://docs.readthedocs.io/en/latest/search.html?q=configuration&check_keywords=yes&area=default which is the default search (instead of the Search As You Type)

### Expected result

I was expecting that it will just send the current query to the backend and do nothing, basically.

In case we want to have a fallback to the default search result, I think the usage of Enter has to be communicated in the UI.

**Comment by dojutsu-user** [comment]
This is the default behavior as of now.
As soon as the user starts typing... He is updated of the current status, in this case -- a message is shown to him -- `Searching ....`.

**Comment by stsewd** [comment]
I think we should _select_ the first result, so when pressing enter the user can go to the page of that result.

**Comment by dojutsu-user** [comment]
@stsewd 
I am not sure that I followed your comment.
Can you explain a little more.

**Comment by stsewd** [comment]
When searching, the popup window should have the first result selected, so when hitting enter, the user goes to the first result. No need to use arrow keys or the mouse to select the first result.

**Comment by dojutsu-user** [comment]
@stsewd 
I don't think setting the first result as default will be good UI.

Also, it is possible to select the results with the ArrowUp and ArrowDown keys.

**Comment by stsewd** [comment]
> Also, it is possible to select the results with the ArrowUp and ArrowDown keys.

Sorry, I had an extension overriding that.

**Comment by dojutsu-user** [comment]
I would like to know what will be good UI.
@readthedocs/core ?

**Comment by agjohnson** [comment]
Normal search function is to perform a search when hitting enter in a search box, we should preserve this. I expect that the search modal results will be updated when I hit enter. I don't expect to be dropped back into the default sphinx search results.

**Comment by dojutsu-user** [comment]
@agjohnson 
Our goal was to provide search-as-you-type capability -- I believe that user shouldn't have to hit enter to get the results.

**Comment by stsewd** [comment]
I'm fixing this in https://github.com/readthedocs/readthedocs-sphinx-search/pull/81. The idea, is to select the first result, but have a link to the original search, this also helps in the case the api is down, so users can still go to the default search.

**Comment by agjohnson** [comment]
> Our goal was to provide search-as-you-type capability -- I believe that user shouldn't have to hit enter to get the results.

Sure, but they are, myself included :slightly_smiling_face: 

If the goal is to block the user from hitting enter, then we should capture this keypress and stop the event from propagating. It is unexpected UX to hit enter, whether accidentally or because you're used to text boxes accepting enter keypress as an action, and being dropped into a different UI.

**Comment by stsewd** [comment]
> I would be surprised to select the first search result automatically.

But having enter do nothing feels weird, having the first item selected by default, so you can use enter to go the page is used by several applications (slack, algolia).

**Comment by humitos** [comment]
I'd expect that when hitting Enter,

- if there are no results yet: results get updated (API is called immediately)
- if there are results and nothing is selected: nothing happens
- if there are results and one is selected: "click" on the selected result and open that page

I'm not 100% sure that we want to select the first result by default. I think it's confusing because if you type something, and hit enter, but milliseconds before you hit enter there were results you will end up in a page that you don't know why (the first result was clicked without notice it)

**Comment by stsewd** [comment]
we are talking about the "search as you type" extension, so it is expected that you don't need to hit enter to search for something. We could change the placeholder to be more explicit like "type to start searching", even in the browser the first item is selected automatically

**Comment by agjohnson** [comment]
> we are talking about the "search as you type" extension, so it is expected that you don't need to hit enter to search for something. 

That's the intended user interaction, but the effective user interaction is going to vary based on the user. We can avoid discrepancies between how people interpret an search as you type input box by making the interaction consistent. Myself, when I see a text box input like this, I assume I'm supposed to hit enter at the end to update the search results. If you don't interpret a search input like this, then you wouldn't press enter and both users would have the same experience.

> But having enter do nothing feels weird

It wouldn't technically be doing nothing, but instead hitting enter could move focus away from the text input box, or could simple trigger a search event (similar to pausing typing), or both. I don't think we need an opinionated event here, but hitting enter needs to provide the user with some feedback.
