### ISSUE TITLE
Unable to get sphinx_search.extension to work

### ISSUE THREAD

**Issue by markcmiller86** [readthedocs/readthedocs-sphinx-search#68]
I've tried to make this work in a small [test case](https://github.com/LLNL/H5Z-ZFP/tree/mcm86-31Aug20-test-rtd-search/docs). Everything I've tried has failed to load the extension.

I tried copying your `conf.py` and `requirements.txt` verbatim used in this repository. That didn't help. It failed on `import sphinx_search`. Here are build failure links (if RTD permits you to follow them...)

* [Attempt 1](https://readthedocs.org/projects/h5z-zfp/builds/11781166/)
  * Just added `'sphinx_search.extension'` to `conf.py` `extensions` variable
* [Attempt 2](https://readthedocs.org/projects/h5z-zfp/builds/11781270/)
  * Included `import sphinx_search` in conf.py
* [Attempt 3](https://readthedocs.org/projects/h5z-zfp/builds/11781403/)
  * Added identical `requirements.txt` file

Can you suggest what I am doing wrong?

**Comment by stsewd** [comment]
Looks like you didn't add the extension 

https://github.com/LLNL/H5Z-ZFP/commit/367dac6d061af9f59fd5b5464bf001ded51bb309#diff-93bd81aa3a2f0c02728220a6b46fb58d

You need `readthedocs-sphinx-search` in your requirements file.

You should also use a rtd configuration file to indicate the path of the requirements file https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by markcmiller86** [comment]
Ok, thanks. I've got it working now.

FYI...I happend to be still running my RTD project on Python 2 also.

That probably contributed to issues I was having.

Thanks
