### ISSUE TITLE
Search popup is unwieldy on desktop (considere using a drop down menu)

### ISSUE THREAD

**Issue by stijn-h** [readthedocs/readthedocs-sphinx-search#73]
Searching is not a pleasant experience, and it's mainly because of a slow, (assumably) mobile-first search popup. While I can't speak for every documentation website, at least for the repository I'm working with (Godot Engine), desktop monitors should be the primary device to target for user experience. Example in the Godot Engine docs:

![search_godot](https://user-images.githubusercontent.com/25907608/91893901-21d34e80-ec95-11ea-8c03-d3e808db59e9.PNG)

A better instant search would only take up a modest amount of space under the search bar, and not take away the ability to use the current page. This would likely imply different search UI on mobile and desktop devices.

**Comment by stsewd** [comment]
> and it's mainly because of a slow, (assumably) mobile-first search popup

Do you mean the transition is slow? It should be faster now https://github.com/readthedocs/readthedocs-sphinx-search/pull/66


> A better instant search would only take up a modest amount of space under the search bar, and not take away the ability to use the current page. This would likely imply different search UI on mobile and desktop devices.

Some other sites like mkdocs have the modal window like this as well https://www.mkdocs.org/.

I guess we can have something like an option to _minimize_ the modal window?

**Comment by hinlopen** [comment]
Those changes should help, but I still feel that it leaves much to be desired. I guess the idea behind the large popup is that search results aren't single line suggestions like in a usual drop down. However, even in the smaller example you gave, it prevents you from using or reading the current page you are on while searching.

**Comment by stsewd** [comment]
> Those changes should help, but I still feel that it leaves much to be desired

Do you mean related to speed?

> However, even in the smaller example you gave, it prevents you from using or reading the current page you are on while searching.

Which example? Do you mean the mkdocs search?

**Comment by hinlopen** [comment]
> Do you mean the mkdocs search?

Yes. I would prefer a list of search suggestions that dont take away control from the webpage, like in [this example](https://requests.readthedocs.io/en/master/).
