### ISSUE TITLE
Use `CTRL+f` to open the search box?

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-sphinx-search#87]
In https://github.com/readthedocs/readthedocs-sphinx-search/pull/31 we added `/` as a hotfix to open the search box which is good.

Today I found that Stripe docs goes a step further here and uses `CTRL+f` which I thought immediately it was a bad decision because "I want to use just the regular search of my browser", but then I saw it says that you can hit `CTRL+f` again to switch to the default search feature :100: 

![Screenshot_2021-03-15_10-35-25](https://user-images.githubusercontent.com/244656/111132886-2cdb3580-857a-11eb-9680-16818be6918b.png)

> NOTE the message and checkbox at the bottom right

You can try it by yourself at https://stripe.com/docs/api/events/types

**Comment by astrojuanlu** [comment]
I'm generally very annoyed when a website intercepts Ctrl+F or any other usual keyboard shortcut like Ctrl+Tab. I wonder if there's some user research available out there.

**Comment by stsewd** [comment]
> I'm generally very annoyed when a website intercepts Ctrl+F or any other usual keyboard shortcut like Ctrl+Tab. I wonder if there's some user research available out there.

same, was just reading the stripe docs, and hijacking my ctrl-f is annoying, didn't even read the "pressing ctrl-f again" suggestion, I just assumed it wasn't possible to have my firefox's search back...

**Comment by astrojuanlu** [comment]
https://twitter.com/killedbygoogle/status/1465196733567320068

Can we close this as won't-fix? 😄

**Comment by humitos** [comment]
Moved the conversation to https://github.com/readthedocs/readthedocs-client/issues/43
