### ISSUE TITLE
Parallel reading warning

### ISSUE THREAD

**Issue by adriangonz** [readthedocs/readthedocs-sphinx-search#91]
After enabling the `sphinx_search.extension` module, we've started to see the following warnings in our Sphinx logs:

```
WARNING: the sphinx_search.extension extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit

WARNING: doing serial read
```

Looking at the Sphinx docs, it seems that Sphinx expects the extension metadata to specify whether it's safe to read / write files in parallel:

https://www.sphinx-doc.org/en/master/extdev/index.html#extension-metadata

These warnings can get quite noisy in our CI/CD pipeline, so it would be great to your thoughts on whether this is something that can be added to this extension's metadata.

**Comment by astrojuanlu** [comment]
Came here to report the same thing 👍🏽
