### ISSUE TITLE
Search as you type panel opens too late and first characters are not typed

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs-sphinx-search#92]
When I click on the search bar and I immediately start typing, 90 % of the times the first characters do not get typed, as demonstrated here:

![search-as-you-type-1](https://user-images.githubusercontent.com/316517/129045215-9d71c0d2-62e3-4dd3-b9cf-2b355c21c450.gif)

It happens to me a lot and it's quite annoying.

**Comment by stsewd** [comment]
I think we can just remove the animation or something like render the search box first

https://github.com/readthedocs/readthedocs-sphinx-search/blob/d857859f851b210e7b2658d9efdc25c8882c0f41/sphinx_search/static/js/rtd_sphinx_search.js#L653-L655 

@nienn may have some better ideas on how to implement this correctly

**Comment by nienn** [comment]
The current script is not grabbing the value from the original search box when the modal first gets shown, so whatever you write there is lost. Only the characters written after the focus changes to the new input are used.

**Comment by nienn** [comment]
I'm not being able to test this locally at the moment, but I believe something is rewriting the original input value before this line
https://github.com/readthedocs/readthedocs-sphinx-search/blob/d857859f851b210e7b2658d9efdc25c8882c0f41/sphinx_search/static/js/rtd_sphinx_search.js#L663-L665

I'll try to do some tests again later.

**Comment by nienn** [comment]
_(I'm still not testing it locally, just debugging with chrome DevTools.)_

There seems to be nothing wrong with the value coming from the original input thought, 
so I think it's just like @stsewd said, related to the animation timing.
 
I would not remove the animation, however. my guess is that the missing characters are lost in the time between the `search_bar.blur()` and the `search_outer_input.focus()`, which is delayed by the animation.

If this is so, simply moving the blur code — lines 646 to 649 — to the beginning of the callback function — line 652 — should do the trick.
https://github.com/readthedocs/readthedocs-sphinx-search/blob/d857859f851b210e7b2658d9efdc25c8882c0f41/sphinx_search/static/js/rtd_sphinx_search.js#L646-L667
